#!/usr/bin/env bash
#script that transfers a file from our client to a server.

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

path_file=$1
ip=$2
username=$3
path_ssh=$4

scp -o "StrictHostKeyChecking=no" -i "$path_ssh" "$path_file" "$username@$ip:~/"


if [ $? -eq 0 ]
then
	echo "FILE WAS TRANSFERED SUCCESSFULLY"
else
	echo "FILE TRANSFER FAILED"
fi
