#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
	log 127.0.0.1 local0 notice
	maxconn 2000
	user haproxy
	group haproxy

defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
	retries	3
	option	redispatch
	timeout	connect	  5000
	timeout	client	 30000
	timeout server	 30000
	errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

frontend http-in
	timeout client	30000
	bind 0:80
	default_backend servers

backend servers
	timeout connect	 3000
	timeout server	30000
	balance roundrobin
        server 208187-web-01 54.172.41.138:80 check
        server 208187-web-01 54.146.89.228:80 check
" >> /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
