#!/bin/bash
chown betty hello
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	3-new_owner

nothing added to commit but untracked files present (use "git add" to track)
