#!/usr/bin/env bash
#loops from 1 to 10, and;
# displays bad luck for the 4th loop iteration,
# displays good luck for the 8th loop iteration,
# displays Best School for the other iterations.

count=0

while [ $count -lt 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luch from china";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done
